config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    get :like, on: :member
  end

  resources :comments

  resource :subscriptions, only: [:create, :destroy]

  resources :blogs

  resource :user, only: [:edit, :show]

  root 'blogs#index'
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :subscriptions
  has_many :users, through: :subscriptions, dependent: :destroy
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :title, presence: true

  def owner(user)
    self.user == user ? "You" : self.user.name
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :find_posts, only: :show
  before_action :authenticate_user!, except: :index

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end 
  end

  def show
    @post = Post.new
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, alert: "Blog was successfully deleted"
  end

  private

    def find_posts
      @posts = @blog.posts.includes(:post_info, :tags).order("post_infos.rating DESC").order(created_at: :desc)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :description)
    end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.slim
div style="margin-left:30%"
  = form_for blog, html: { style: "width:60%" } do |f|

    = render partial: "layouts/errors", locals: { record: blog }


    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"

    .form-group
      = f.label :description
      = f.text_area :description, class: "form-control"

    .actions
      = f.submit class: "btn btn-success"

app/views/blogs/edit.html.slim
h1 style="margin-left:50px" = "Editing Blog"

= render 'form', blog: @blog

br

div style="margin-left:30%"
  = link_to 'Show', @blog, class: "btn btn-info", style: "margin-right:10px;"
  = link_to 'Back', blogs_path, class: "btn btn-warning"

app/views/blogs/index.html.slim
h1 style="margin-left:50px" = "Blogs"

table.table.table-striped align="center" style="width:60%"
  thead
    tr
      th = "Title"
      th = "Owner"
      th

  tbody
    - @blogs.each do |blog|
      tr
        td 
          = link_to blog.title, blog
        td
          = blog.owner(current_user)
        td align="right"
          = link_to 'Show', blog, class: "btn btn-info", style: "margin-right:10px;"

          - if blog.user == current_user
            = link_to 'Edit', edit_blog_path(blog), class: "btn btn-info", style: "margin-right:10px;"
            = link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "margin-right:10px;"

          - if blog.users.include?(current_user)
            = link_to "Unsubscribe", subscriptions_path(params: { id: Subscription.where(blog_id: blog.id, user_id: current_user.id).first.id }), method: :delete, class: "btn btn-danger"
          - elsif current_user
            = link_to "Subscribe", subscriptions_path(params: { blog: blog.id, user: current_user.id }), method: :post, class: "btn btn-success"

br

center
  = link_to 'New blog', new_blog_path, class: "btn btn-success"

app/views/blogs/new.html.slim
h1 style="margin-left:50px" = "New blog"

= render 'form', blog: @blog

br

= link_to 'Back', blogs_path, class: "btn btn-warning", style: "margin-left:30%;"

app/views/blogs/show.html.slim
h1 style="margin-left:50px" = "Blog"

table.table.table-striped align="center" style="width:60%"
  tbody
    tr
      td 
        strong = "Title"
      td
        = @blog.title

    tr
      td
        strong = "Description"
      td
        = @blog.description

    tr
      td
        strong = "Owner"
      td
        = @blog.owner(current_user)

center
  - if @blog.user == current_user
    = link_to 'Edit', edit_blog_path(@blog), class: "btn btn-info", style: "margin-right:10px;"
  = link_to 'Back', blogs_path, class: "btn btn-warning"

- if @blog.user == current_user
  = render partial: 'posts/new', locals: { post: @post, blog: @blog } 

= render partial: 'posts/index', locals: { posts: @posts, blog: @blog }