config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    get :like, on: :member
  end

  resources :comments

  resource :subscriptions, only: [:create, :destroy]

  resources :blogs

  resource :user, only: [:edit, :show]

  root 'blogs#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :post, presence: true
  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_comment, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to @comment.post, notice: "Comment was succesfully created"
    else
      redirect_to @comment.post, notice: "Sorry, can't create a comment"
    end

  end

  def update 
  end

  def destroy
    @comment.destroy
    redirect_to @comment.post, notice: "Comment was succesfully deleted"
  end

  private

    def comment_params
      params.require(:comment).permit(:text)
    end

    def get_comment
      @comment = Comment.find(params[:id])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
div style="margin-left:30%"
  = form_for comment, html: { style: "width:60%" } do |f|

    = render partial: "layouts/errors", locals: { record: comment }

    .form-group
      = f.label :text
      = f.text_field :text, class: "form-control"


    .actions
      = hidden_field_tag 'post_id', post.id
      = f.submit class: "btn btn-success"

app/views/comments/_index.html.slim
h1 style="margin-left:50px" = "Comments"

table.table.table-striped align="center" style="width:60%"
  thead
    tr
      th = "Text"
      th = "Username"
      th

  tbody
    - @comments.each do |comment|
      tr
        td 
          = comment.text
        td
          = comment.user.first_name

        td align="right"

          - if comment.user == current_user
            = link_to 'Edit', edit_comment_path(comment), class: "btn btn-info", style: "margin-right:10px;"
            = link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", style: "margin-right:10px;"

br

app/views/comments/_new.html.slim
h1 style="margin-left:50px" = "New Comment"

= render 'comments/form', { comment: @comment, post: @post }

br

= link_to 'Back', root_path, class: "btn btn-warning", style: "margin-left:30%;"

app/views/comments/edit.html.slim
h1 style="margin-left:50px" = "Editing Post"

= render 'form', { comment: @comment, post: @comment.post }

br

div style="margin-left:30%"
  = link_to 'Back', posts_path, class: "btn btn-warning"