config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    get :like, on: :member
  end

  resources :comments

  resource :subscriptions, only: [:create, :destroy]

  resources :blogs

  resource :user, only: [:edit, :show]

  root 'blogs#index'
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_post_info, on: :create

  belongs_to :user
  belongs_to :blog
  has_one :post_info
  has_and_belongs_to_many :tags
  has_many :comments

  validates :user, presence: true
  validates :blog, presence: true
  validates :title, presence: true

  def owner(user)
    self.user == user ? "You" : self.user.name
  end

  def tag_names
    tags.pluck(:name)
  end

  def new_tags
  end

  def likes
    post_info.likes
  end

  def views
    post_info.views
  end

  def rating
    post_info.rating
  end

  protected

    def create_post_info
      PostInfo.create(post: self)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :find_comments, only: :show
  before_action :find_blog, only: [:show, :edit, :update]
  before_action :authenticate_user!


  # GET /posts
  # GET /posts.json
  def index
    # raise params.inspect
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:post_info, :tags).order("post_infos.rating DESC").order(created_at: :asc).to_a.uniq
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.post_info.views + 1
    @post.post_info.update(views: views)

    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user
    @post.blog_id = params[:blog_id]

    @blog = Blog.find(params[:blog_id])

    @post.tag_ids = params[:post][:tags].delete_if { |a| a == "" }

    if params[:post][:new_tags]

      @tag_names = params[:post][:new_tags].split(/\W+/)

      @tag_names.map { |tag_name| Tag.new(name: tag_name, post_ids: [@post.id]).save }

    end

    if @post.save
      redirect_to @post.blog, notice: 'Post was successfully created.'
      send_mails
    else
      render :new
    end
  end

  def like
    @likes = @post.post_info.likes + 1
    @post.post_info.update(likes: @likes)
    redirect_to @post.blog
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def find_blog
      @blog = @post.blog
    end

    def find_comments
      @comments = @post.comments.order(created_at: :desc)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :tags)
    end

    def send_mails
      @blog = @post.blog
      @blog.users.each do |user|
        UserMailer.new_post_email(user, @blog).deliver_now
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
div style="margin-left:30%"
  = form_for post, html: { style: "width:60%" } do |f|

    = render partial: "layouts/errors", locals: { record: post }

    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control"

    .form-group
      = f.label :text
      = f.text_area :text, class: "form-control"

    .form-group
      = f.label :tags
      = f.collection_select :tags, Tag.all, :id, :name, { include_blank: true }, { class: "form-control", multiple: true  }

    .form-group
      = f.label :new_tags
      = f.text_field :new_tags, value: "", class: "form-control"

    .actions
      = hidden_field_tag 'blog_id', @blog.id
      = f.submit class: "btn btn-success"

app/views/posts/_index.html.slim
h1 style="margin-left:50px" = "Posts"

table.table.table-striped align="center" style="width:60%"
  thead
    tr
      th = "Title"
      th = "Text"
      th = "Username"
      th

  tbody
    - @posts.each do |post|
      tr
        td 
          = link_to post.title, post
        td 
          = post.text
        td
          = post.owner(current_user)

        td align="right"

          = link_to 'Show', post, class: "btn btn-info", style: "margin-right:10px;"

          - if post.user == current_user
            = link_to 'Edit', edit_post_path(post), class: "btn btn-info", style: "margin-right:10px;"
            = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", style: "margin-right:10px;"

          = link_to "Like", like_post_path(post), class: "btn btn-danger"

      tr 
        td
          
        td
          = "Comments: "
          = post.comments.count
          
        td
          = "Tags: "
          - post.tags.each do |tag|
            = link_to tag.name, posts_path(params: { q: { tags_name_eq: tag.name } })
            = ", "

        td style="text-align:right;"
          = "Views: "
          = post.views
          = "  Likes: "
          = post.likes
          = "  Rating: "
          = post.rating

br

/ center
/   = link_to 'New Post', new_post_path, class: "btn btn-success"

app/views/posts/_new.html.slim
h1 style="margin-left:50px" = "New Post"

= render 'posts/form', post: @post

br

= link_to 'Back', root_path, class: "btn btn-warning", style: "margin-left:30%;"

app/views/posts/edit.html.slim
h1 style="margin-left:50px" = "Editing Post"

= render 'form', post: @post

br

div style="margin-left:30%"
  = link_to 'Show', @post, class: "btn btn-info", style: "margin-right:10px;"
  = link_to 'Back', posts_path, class: "btn btn-warning"

app/views/posts/index.html.slim
= render partial: 'posts/index'

app/views/posts/new.html.slim
= render partial: "posts/new"

app/views/posts/show.html.slim
h1 style="margin-left:50px" = "Post"

table.table.table-striped align="center" style="width:60%"
  tbody
    tr
      td 
        strong = "Title"
      td
        = @post.title

    tr
      td
        strong = "Text:"
      td
        = @post.text

center
  - if @post.user == current_user
    = link_to 'Edit', edit_post_path(@post), class: "btn btn-info", style: "margin-right:10px;"
  = link_to 'Back', @post.blog, class: "btn btn-warning"

= render partial: "comments/new", locals: { post: @post, comment: @comment }

= render partial: "comments/index", locals: { post: @post, comment: @comment }